# Generated by Django 5.1.1 on 2024-10-07 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pagador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('mercadoPago', 'MercadoPago'), ('transferencia', 'Transferencia Bancaria')], max_length=20)),
                ('nombre_tarjeta', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=16, null=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.pagador')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('destinatario', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.metodopago')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.pagador')),
            ],
        ),
    ]
