# Generated by Django 5.1.1 on 2024-10-08 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=16)),
                ('fecha_expiracion', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('tipo', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='fecha_expiracion',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='nombre_tarjeta',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='numero_tarjeta',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='tarjeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.tarjeta'),
        ),
    ]
