# Generated by Django 5.1.1 on 2024-10-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_tarjeta_remove_metodopago_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinatario',
            name='email',
        ),
        migrations.AlterField(
            model_name='pagador',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pagador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
