# Generated by Django 5.1.1 on 2024-10-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_rename_fecha_expiracion_tarjeta_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='usuario',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='esReembolso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(default='Tarjeta', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('valido', 'Valido'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
    ]
