# Generated by Django 5.1.1 on 2024-10-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_destinatario_email_destinatario_idexterna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
