# Generated by Django 5.1.1 on 2024-10-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_alter_destinatario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='idExterna',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pagador',
            name='idExterna',
            field=models.IntegerField(),
        ),
    ]
