# Generated by Django 5.1.1 on 2024-10-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_alter_destinatario_idexterna_alter_pagador_idexterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='cuotas',
            field=models.IntegerField(blank=True, choices=[(3, '3 Cuotas'), (6, '6 Cuotas'), (12, '12 Cuotas')], null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='enCuotas',
            field=models.BooleanField(default=False),
        ),
    ]
