# Generated by Django 5.1.1 on 2024-10-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_remove_pagador_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='metodo_pago',
        ),
    ]
