# Generated by Django 5.1.1 on 2024-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_remove_transaccion_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagador',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
