# Generated by Django 5.1.1 on 2024-10-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_pagador_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagador',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
