# Generated by Django 5.1.1 on 2024-10-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_alter_pagador_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.metodopago'),
        ),
    ]
