# Generated by Django 5.1.1 on 2024-10-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0014_transaccion_metodo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinatario',
            old_name='idExterna',
            new_name='id_externa',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='enCuotas',
            new_name='en_cuotas',
        ),
        migrations.RenameField(
            model_name='pagador',
            old_name='idExterna',
            new_name='id_externa',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='esReembolso',
            new_name='es_reembolso',
        ),
    ]
