# Generated by Django 5.1.1 on 2024-10-10 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0015_rename_idexterna_destinatario_id_externa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.destinatario'),
        ),
    ]
