# Generated by Django 5.1.1 on 2024-10-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0018_tarjeta_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='dni',
            field=models.CharField(max_length=8),
        ),
    ]
