# Generated by Django 5.1.1 on 2024-10-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0020_remove_transaccion_es_reembolso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('valido', 'Valido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.destinatario')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.pagador')),
            ],
        ),
    ]
