# Generated by Django 5.1.1 on 2024-11-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0021_reembolso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinatario',
            name='id_externa',
        ),
        migrations.RemoveField(
            model_name='destinatario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='pagador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='pagador',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='pagador',
            name='id_externa',
        ),
        migrations.RemoveField(
            model_name='pagador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='destinatario',
            name='double_beds_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='hotel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='id_external',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='images',
            field=models.CharField(default='default_image.jpg', max_length=250),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='name',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='single_beds_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='state',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AddField(
            model_name='pagador',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='pagador',
            name='document',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagador',
            name='id_external',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagador',
            name='name',
            field=models.CharField(default='hola', max_length=100),
        ),
        migrations.AddField(
            model_name='pagador',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagador',
            name='surname',
            field=models.CharField(default='hola', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='client',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='end_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_external',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='services',
            field=models.CharField(default='hola', max_length=250),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='start_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
