# Generated by Django 5.1.1 on 2024-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0022_remove_destinatario_id_externa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='client',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='end_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='id_external',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='services',
            field=models.CharField(default='hola', max_length=250),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='start_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
